name: Develop Branch Action

on:
  push:
    branches:
      - develop

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from Main Branch
        run: echo "Hello, triggered from develop branch!"
