name: Main Branch Action

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from Main Branch
        run: echo "Hello, triggered from main branch!"
